### ISSUE TITLE
Minor issue: gen-obfuscated.pl vba output detected 1/35 by gdata

### ISSUE THREAD

**Issue by Macleodsolutions** [xor-function/fathomless#1]
Went to demo this to a friend as I'd seen it demonstrated a couple months ago and noticed it now faces a singular detection by gdata

**Comment by xor-function** [comment]
I updated the generated output for vba code, let me know if this works for you.

**Comment by xor-function** [comment]
Tested modified obfuscation engine by generating a vba macro and adding it to a office document. Uploaded the stand alone code and infected office document to virustotal, no detection 0/54.
